### ISSUE TITLE
JSON simple array loops

### ISSUE THREAD

**Issue by refortie** [Azure/LogicAppsUX#2746]
### Describe the Bug with repro steps 

```yml
$version: 1
$input: JSON
$output: JSON
$sourceSchema: SmokeInput.json
$targetSchema: SmokeOutput.json
root:
  NumberArray1:
    $for(/root/Nums/*): Num
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/37600290/71c687ca-2e28-4f04-b0fc-52efee9ed4ed>)

### Version

Dev

### Additional context

*No response*

AB#24272415
