### ISSUE TITLE
Designer View has different content from Code View

### ISSUE THREAD

**Issue by seplee** [Azure/LogicAppsUX#2777]
### Describe the Bug with repro steps

1. Compose a workflow in a workflow.json file locally using the vscode LogicApp extension.
2. Zip and deploy the workflow to a Standard Logic App. Use the ADO pipeline tasks below.
3. Login to Azure Portal and view the new workflow.
4. Make changes to the workflow in Azure portal. Save those changes.
5. Edit the workflow.json file locally.
6. repeat step 2
7. Login to Azure Portal and view the new workflow.
8. Note that the Code View has the changes you made locally and that the Design View does not.

ADO pipeline tasks from step 2
```
steps:
  - task: ArchiveFiles@2
    displayName: "Create project zip"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/LogicApp"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/LogicApp/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: AzureFunctionApp@1
    displayName: "Deploy Logic App workflows"
    inputs:
      azureSubscription: $(servicePrincipleName)
      appType: "functionAppLinux"
      appName: $(logicAppName)
      package: "$(Build.ArtifactStagingDirectory)/LogicApp/$(Build.BuildId).zip"
      deploymentMethod: "zipDeploy"
```

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Code View
![image](https://github.com/Azure/LogicAppsUX/assets/96065267/316ddb65-14d9-4ddf-8761-214846b087a8)

### Design View
![image](https://github.com/Azure/LogicAppsUX/assets/96065267/bd38c717-64f8-4fac-a789-7cb72c850738)

### Browser

Brave

AB#24310199
