### ISSUE TITLE
Data Mapper designer hangs when opening a map with format-datetime placeholders

### ISSUE THREAD

**Issue by chris-w-dev** [Azure/LogicAppsUX#3714]
### Describe the Bug with repro steps

The designer hangs when opening a map file containing a `format-datetime` with multiple formatting placeholders like `[Y0001]-[M01]-[D01]`. Creating the map file, saving it, and generating the XSLT works perfectly. But after you close the designer and try to open the saved map file again, the designer surface hangs. The only workaround is to replace the formatting placeholders for that function with an empty string, opening the designer and putting the placeholder string back in.

Reproduction steps:
1. Create a new mapping definition:
  ```yaml
  $version: 1
  $input: JSON
  $output: JSON
  $sourceSchema: SourceSchemaJson.json
  $targetSchema: TargetSchemaJson.json
  root:
    String1: format-datetime(/root/shipDate, "[Y0001]-[M01]-[D01]")
  ```
2. Choose Data Mapper: Load existing data map
3. Designer surface shows, but will not load completely and hangs.

### Version

v2.81.5

AB#25891061
