### ISSUE TITLE
Data Mapper cannot find schemas after updating extension to v2.86.2

### ISSUE THREAD

**Issue by chris-w-dev** [Azure/LogicAppsUX#3836]
### Describe the Bug with repro steps

After updating the VSCode extension to version v2.86.2, Data Mapper tries to load schema files from folder `<project root>\workflow-designtime\Artifacts\Schemas` while they are actually located in `<project root>\Artifacts\Schemas`.
Not sure if this change was intentionally or not.

*Reproduction steps:*
1. Create a new Logic App project
2. Close and reopen VSCode to enforce creation of folder workflow-designtime
3. Add schema.json to folder <project root>\Artifacts\Schemas
   ```json
   {
     "type": "object",
     "properties": {
       "prop1": {
         "type": "string"
       }
     }
   }
   ```
4. Add test.lml file to folder <project root>\Artifacts\MapDefinitions
   ```yaml
   $version: 1
   $input: JSON
   $output: JSON
   $sourceSchema: schema.json
   $targetSchema: schema.json
   root:
     prop1: /root/prop1
   ```
5. Load existing data map test.lml in designer

*Result:*
 - Extension version v2.81.5: designer loads succesfully
 - Extension version v2.86.2: designer returns an error while loading data map:
   ```
   Error loading Data Mapper resource: "400 - InvalidRequestContent: The schema file '<project root>\workflow-designtime\Artifacts\Schemas\schema.json' could not be found."
   ```

### Version

v2.86.2
