### ISSUE TITLE
Nested conditional is not deserialized correctly

### ISSUE THREAD

**Issue by chris-w-dev** [Azure/LogicAppsUX#4346]
### Describe the Bug with repro steps 

There are a couple of scenarios for an `If` function where a map definition can be created, saved, and an XSLT can be generated correctly as long as the designer is not closed. When the designer is closed and reopened for such a map definition, it either cannot be loaded at all (black screen) or different nodes and edges are missing.

1. `If` on a property nested in a conditional object does not show up in the designer. 

```yaml
$version: 1
$input: JSON
$output: JSON
$sourceSchema: schema.json
$targetSchema: schema.json
root:
  $if(/root/OrderNo):
    Object1:
      $if(/root/salesOrg):
        String1: /root/Object1/String1
```

Before:

![nested-if-before](<https://github.com/Azure/LogicAppsUX/assets/84322101/95e569db-4fc7-4854-b53c-a11574343876>)

After reloading:

![nested-if-after](<https://github.com/Azure/LogicAppsUX/assets/84322101/9a7e5f9e-ea14-4436-b971-2ae80c2edae9>)

2. Same scenario as 1 with a function in the nested `If` results in a black screen.

```yaml
$version: 1
$input: JSON
$output: JSON
$sourceSchema: schema.json
$targetSchema: schema.json
root:
  $if(/root/OrderNo):
    Object1:
      $if(/root/salesOrg):
        String1: lower-case(/root/Object1/String1)
```

Before:

![nested-if-function-before](<https://github.com/Azure/LogicAppsUX/assets/84322101/278b86f4-4141-4f03-ba58-04a2b1c02aa2>)

3. `If` with a function as value nested in a `For` renders the function incorrectly as a string

```yaml
$version: 1
$input: JSON
$output: JSON
$sourceSchema: schema.json
$targetSchema: schema.json
root:
  ComplexArray1:
    $for(/root/Nums/*):
      $if(Num):
        F1: multiply(Num, 2)
```

Before: 

![if-function-in-for-before](<https://github.com/Azure/LogicAppsUX/assets/84322101/b50208d3-3f73-4f23-bc0b-5e635d25cf00>)

After reloading: 

![if-function-in-for-after](<https://github.com/Azure/LogicAppsUX/assets/84322101/888fd882-c95f-4569-a05c-b88fbdf79f51>)

4. Same scenario as 3 with an index reference instead of a function, which renders the index also incorrectly as a string

```yaml
$version: 1
$input: JSON
$output: JSON
$sourceSchema: schema.json
$targetSchema: schema.json
root:
  ComplexArray1:
    $for(/root/Nums/*, $a):
      $if(Num):
        F1: $a
```

Before: 

![if-index-in-for-before](<https://github.com/Azure/LogicAppsUX/assets/84322101/cc54b492-6f65-410c-bf94-6ddca7e36d54>)

After reloading: 

![if-index-in-for-after](<https://github.com/Azure/LogicAppsUX/assets/84322101/0a83466f-06df-45c5-85da-99a43cbacb9b>)

Schema:

```json
{
    "type": "object",
    "properties": {
        "OrderNo": {
            "type": "string"
        },
        "salesOrg": {
            "type": "string"
        },
        "Object1": {
            "type": "object",
            "properties": {
                "String1": {
                    "type": "string"
                }
            }
        },
        "Nums": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "Num": {
                            "type": "integer"
                        }
                    }
                }
            ]
        },
        "ComplexArray1": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "F1": {
                            "type": "integer"
                        }
                    }
                }
            ]
        }
    }
}
```

### Screenshots or Videos

*No response*

### Version

v2.119.4

### Additional context

*No response*
